gamefaqs_project/urls.py
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

from authentication import views as auth_view
from accounts import views as user_view
from accounts.views import (
    favorite_game_view,
    follower_view,
    unfavorite_game_view,
    unfollow_view,
    user_profile_view,
    favorite_game_view,
    user_list_view,
)
from game.views import (
    AddGameView,
    AllGameView,
    GameTitleView,
    PlatformView,
    Search,
)
from error_pages.views import (
    error_404_view,
    error_500_view,
)
from post.views import (
    PostCreate,
    PostDetailView,
    PostListView,
    add_comment_to_post,
)


urlpatterns = [
    # Core links
    path("", user_view.index, name="homepage"),
    path("admin/", admin.site.urls, name="admin"),
    # Game Related Links
    path("viewGames/", AllGameView.as_view(), name="games"),
    path("viewGames/<int:game_id>/", GameTitleView, name="game-title"),
    path("newGame/", AddGameView.as_view(), name="add-game"),
    path("viewGames/platform/<str:platform>/", PlatformView, name="platform"),
    path("viewGames/search/<str:title>/", Search, name="search"),
    # Auth Links
    path("login/", auth_view.login_view, name="login"),
    path("signup/", auth_view.signup_view, name="signup"),
    path("logout/", auth_view.logout_view, name="logout"),
    # Post Links
    path("post/add/", PostCreate.as_view(), name="post-create"),
    path("posts/<int:pk>/", PostDetailView.as_view(), name="post_detail"),
    path("posts/", PostListView.as_view(), name="post-list"),
    path("post/<int:pk>/comment/", add_comment_to_post, name="add_comment_to_post"),
    # Follow Links
    path("follow/<int:user_id>/", follower_view, name="follow"),
    path("unfollow/<int:user_id>/", unfollow_view, name="unfollow"),
    # User/Profile Links
    path("user/<int:CustomUser_id>/", user_profile_view, name="user-profile"),
    # path("viewProfile/<str:username>/", user_profile_view, name="profile"),
    path("viewUsers/", user_list_view, name="users"),
    # Favorites
    path("favorite_game/<int:game_id>/", favorite_game_view, name="favorite_game"),
    path("unfavorite_game/<int:game_id>/", unfavorite_game_view, name="unfavorite_game"),
    # Statics
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# TODO Add other errors
handler404 = "error_pages.views.error_404_view"
handler500 = "error_pages.views.error_500_view"

game/models.py
from django.db import models


class Game(models.Model):
    PLATFORM_CHOICES = (
        ("PC", "PC"),
        ("PS5", "PS5"),
        ("XSX", "XSX"),
        ("Switch", "Switch"),
        ("iOS", "iOS"),
        ("Android", "Android"),
        ("Arcade", "Arcade"),
        ("PS4", "PS4"),
        ("PS3", "PS3"),
        ("Xbox One", "Xbox One"),
        ("Xbox 360", "Xbox 360"),
        ("Sega", "Sega"),
        ("Wii U", "Wii U"),
        ("Wii", "Wii"),
        ("PSP", "PSP"),
        ("Vita", "Vita"),
        ("3DS", "3DS"),
        ("RetoPy", "RetoPy"),
        ("Other Systems", "Other Systems"),
    )
    title = models.CharField(max_length=40, null=True, blank=True)
    description = models.TextField()
    platform = models.CharField(max_length=50, choices=PLATFORM_CHOICES)
    cover_art = models.ImageField(
        upload_to="cover-art/",
        blank=True,
        null=True,
        default="cover-art/cover-art-default.png",
    )

    def __str__(self):
        return f"{self.title} | {self.platform}"

templates/add-game.html
{% extends "base.html" %} {% block content %}
<div class="add-game-form-container">
  <div class="row">
    <div class="col-md-12">
      <div class="add-game-template">
        <h1 class="add-game-title">Add a new game</h1>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %} {{form.media}} {{form.as_p}}
          <input type="submit" value="submit" />
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/add_comment_to_post.html
{% extends 'base.html' %} {% block content %}
<br />
<h1 class="comment-title">New comment</h1>
<form method="POST" class="post-form" enctype="multipart/form-data">
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" value="Post" />
</form>
{% endblock %}

templates/add_post.html
{% extends "base.html" %} {% block content %}
<div class="add-post-form-container" style="color: #fff">
  <div class="row">
    <div class="col-md-12">
      <div class="add-post-template">
        <h1 class="add-post-title">Add a post</h1>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %} {{form.media}} {{form.as_p}}
          <input type="submit" value="submit" />
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/all-users.html
{% extends "base.html" %} {% block content %}
<div class="container-img">
  <br />
  <div class="testing">
    <div class="container">
      <div class="row profile">
        <div class="col-md-3">
          <div class="profile-sidebar">
            <h1 class="user-list-title">Online</h1>
            <div class="user-list-container">
              <br />
              {% for items in user %}
              <div>
                <a class="online-users" href="/user/{{items.id}}">
                  {{items.username}}
                </a>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
        <h1 class="user-list-title">View all users</h1>
        <div class="user-list-container">
          <br />
          {% for users in all_users %}
          <div>
            <a class="all-users" href="/user/{{users.id}}">
              {{users.username}}
            </a>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  {% endblock %}
</div>

templates/game-info.html
{% extends "base.html" %} {% block content %}
<div class="game-info-container">
  <div class="row">
    <div class="col-md-12">
      <div class="game-info-template">
        <h1 class="game-title-detail">{{game.title}}</h1>
        <span class="platform-detail-title">On: {{platform}}</span>
        <br />
        <br />
        <img src="{{game.cover_art.url}}" width="500px" height="500px" />
        <br />
        <br />
        <div class="game-detail">
          About {{game.title}}: <br />
          {{game.description}}
        </div>
        <a href="/favorite_game/{{game.id}}">
          <input type="submit" value="Favorite" />
        </a>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/generic-form.html
{% extends "base.html" %} {% load static %} {% block content %}
<div class="generic-form-container">
  <div class="gen-form-temp">
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %} {{form.as_p}}
      <input type="submit" value="Submit!" />
    </form>
  </div>
</div>
{% endblock %}

templates/index.html
{% extends "base.html" %} {% block content %}
<div className="container">
  <div class="row">
    <div class="col-md-12">
      <div class="landing-template">
        <div class="user-box">
          <div class="landing-profile-view">
            <h1 class="homepage-title">{{user.username}}</h1>
            {% if user.avatar %}
            <img
              src="{{user.avatar.url}}"
              alt=" User Avatar"
              width="100"
              height="100"
              style="border-radius: 50%"
            />
            {% else %}
            <img
              src="https://vectorified.com/images/facebook-no-profile-picture-icon-26.jpg"
              alt=" User Avatar"
              width="100"
              height="100"
            />
            {% endif %}
            <p>Email: {{user.email}}</p>
            <p>Platform: {{user.platform_choice_field}}</p>
            <p class="about-me">About Me: {{user.bio}}</p>
          </div>
          <div class="posts-div">
            <h4 class="homepage-title">Your Most Recent Posts</h4>
            {% if posts %} {% for post in posts %}
            <div class="small-posts-box">
              <li>
                <a id="home-post" href="posts/{{post.id}}">{{post.topic}}</a>
              </li>
            </div>
            {%endfor%} {% else%}
            <p class="no-recent">You haven't made any post yet... 🥺</p>
            <p>
              <a class="no-recent1" href="/post/add/"
                >Create you own post! 💪</a
              >
              {% endif %}
            </p>
          </div>
        </div>
        <div class="bottom-div">
          <div class="posts-div-2">
            <h4 class="homepage-title">New Gamrs</h4>
            {% for users in users_list %}
            <div class="small-users-box">
              <p>
                <a href="/user/{{users.id}}/" id="game-feed-title"
                  >{{users.username}}</a
                >
                Plays On:
                <a
                  class="landing-games-list"
                  href="/viewGames/platform/{{users.platform_choice_field}}/"
                  >{{users.platform_choice_field}}</a
                >
              </p>
            </div>
            {%endfor%}
          </div>
          <div class="posts-div-2">
            <h4 class="homepage-title">Suggested Game</h4>
            {% if games %} {% for game in games %}
            <div class="landing-games-list">
              <a>
                <p>
                  <img
                    src="{{game.cover_art.url}}"
                    alt="Game Cover Art"
                    width="150"
                    height="150"
                  />
                  &nbsp;
                  <a class="landing-games-list" href="viewGames/{{game.id}}"
                    >{{game.title}}</a
                  >
                  -
                  <a
                    class="landing-games-list"
                    href="viewGames/platform/{{game.platform}}/"
                  >
                    {{game.get_platform_display}}</a
                  >
                </p>
                {%endfor%}
              </a>
            </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %} {% block content %}
<div class="login-form-container">
  <div class="row">
    <div class="col-md-12">
      <div class="login-template">
        <form class="signup-form" method="post">
          {% csrf_token %} {{ form.as_p }}
          <input type="submit" value="Login" />
          <p>
            <a class="signup-form-link" href="/signup/">Become a GAMR</a>
          </p>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/platform.html
{% extends "base.html" %} {% block content %}
<div class="platform-container">
  <div class="row">
    <div class="col-md-12">
      <div class="platform-template">
        <h1 class="platform-title">Games on:</h1>
        {% for items in games %}
        <li>
          <a class="platform-list" href="/viewGames/{{items.id}}">
            {{items.title.title}} - {{items.get_platform_display}}
          </a>
        </li>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/post_detail.html
{% extends "base.html" %} {% block content %}
<div className="post-detail-container">
  <div class="row">
    <div class="col-md-12">
      <div class="post-detail-template">
        <h1 class="post-title">Topic: {{ object.topic }}</h1>
        <p>Poster: {{ object.user_posted }}</p>
        <h2>{{ object.game }}</h2>
        <img
          src="{{object.thumbnail.url}}"
          alt="post thumbnail"
          height="500px"
          width="500px"
        />
        <p class="post-text">{{ object.text }}</p>
        <p class="date">Published: {{ object.post_date }}</p>
      </div>
    </div>
  </div>
</div>
<div class="comment-container">
  {% if user.is_authenticated %}
  <a class="btn btn-warning" href="{% url 'add_comment_to_post' pk=post.pk %}"
    >Leave your comment</a
  >
  {% else %}
  <p>
    You must be logged in to leave a comment <br /><a
      class="login-here"
      href="/login/"
      >Login Here</a
    >
    --
    <a class="signup-here" href="/singup/">Signup Here</a>
  </p>
  {%endif%}
  <hr />
  {% for comment in post.comments.all %}
  <div class="comment">
    <span class="author"><strong>{{ comment.author}}</strong></span>
    <span class="comment-text" style="color: #fff">
      <p>{{ comment.text|linebreaks }}</p>
    </span>
    <div class="date">{{ comment.created_date }}</div>
    <hr />
  </div>
  {% empty %}
  <p>Claim Firsties!</p>
</div>
{% endfor %} {% endblock %}

templates/search.html
{% extends "base.html" %} {% block content %}
<div class="search-results-container">
  <br />
  <h1 class="search-results-title">Heres what we found for you</h1>
  {% if games %} {% for items in games %}
  <li>
    <a class="search-result" href="/viewGames/{{items.id}}">
      {{ items.title.title }}<br />
    </a>
    {% endfor %} {% else %}
    <h1>&#x1F914; No results found &#x1F914;</h1>
    <a class="search-add-game" href="/newGame/" role="tab">Add your game</a>
  </li>
  {% endif %}
</div>
{% endblock %}

templates/signup.html
{% extends "base.html" %} {% block content %}
<div class="signup-form-container">
  <div class="row">
    <div class="col-md-12">
      <div class="singup-template">
        <form class="signup-form" method="post" enctype="multipart/form-data">
          {% csrf_token %} {{ form.as_p }}
          <input type="submit" value="Drink Verification Can" />
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/user_profile.html
{% extends "base.html" %} {% block content %}
<div class="container-img">
  <br />
  <div class="testing">
    <div class="container">
      <div class="row profile">
        <div class="col-md-3">
          <div class="profile-sidebar">
            <div class="profile-userpic">
              <img
                src="{{user.avatar.url}}"
                class="img-responsive"
                alt="Avatar"
              />
            </div>
            <div class="profile-usertitle">
              <div class="profile-usertitle-name">{{user.username}}</div>
              <div class="profile-usertitle-job">{{user.fullname}}</div>
            </div>

            <div class="profile-userbuttons">
              <!-- ##### TODO Set this up or remove it.###### -->
              {% if  user.id != request.user.id %}


              <a href="/follow/{{user.id}}">
                  <button type="button" class="btn btn-success btn-sm" >
                    Follow
                  </button>
              </a>

              {% endif %}



              <button type="button" class="btn btn-success btn-sm">
                <a id="email-link" href="mailto:{{user.email}}" target="_blank"
                >{{user.email}}</a
                >
              </button>
              <div>
                <h3>Follows:</h3>
                <!-- FOLLOWERS -->
                {% for items in followers %}
                  <p>
                      <a href="/user/{{items.id}}/">
                        {{items}}
                      </a>
                    </p>
                {% endfor %}

              </div>
            </div>
            <div>
              <div class="portlet light bordered" id="stats">
                <div class="row list-separated profile-stat">
                  <div class="col-md-4 col-sm-4 col-xs-6">
                    <div class="uppercase profile-stat-text">Online</div>
                    <div class="uppercase profile-stat-title">
                      {{user.is_online}}
                    </div>
                  </div>
                  <div class="col-md-4 col-sm-4 col-xs-6">
                      <div class="profile-stat-text">Joined on</div>
                    <div class="profile-stat-title">
                      {{user.date_joined}}
                    </div>
                  
                  </div>
                  <div class="col-md-4 col-sm-4 col-xs-6">
                    <div class="profile-stat-text">Platform</div>
                    <div class="profile-stat-title">
                      {{user.platform_choice_field}}
                    </div>
                  </div>
                </div>
                <div>
                  <h4 class="profile-desc-title">{{user.username}}'s Bio:</h4>
                  <span class="profile-desc-text"> {{user.bio}} </span>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-9" id="profile-hero">
          <div class="profile-content"></div>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}
</div>